name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly, 1.31.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo bench --verbose
        if: ${{ matrix.rust == 'nightly' }}
      - run: cargo clippy
        continue-on-error: true
